name: PR Deployment

on:
  pull_request:
    types: [ closed ] # Trigger on PR open, sync, and close
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed

jobs:
  cleanup_on_close:
    runs-on: ubuntu-latest
    env:
      SUBDOMAIN: "${{ github.event.number }}-${{ github.head_ref }}"
      PATH_PM2: /root/.nvm/versions/node/v18.20.2/bin/pm2
      DOMAIN_ADDRESS: web7.pro
      SUBDOMAIN_ADDRESS: stage-${{ github.event.number }}.web7.pro
    steps:
      - name: Configure Nginx on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            source ~/.bashrc
            sudo rm /etc/nginx/sites-available/${{ env.SUBDOMAIN_ADDRESS }}
            sudo rm /etc/nginx/sites-enabled/${{ env.SUBDOMAIN_ADDRESS }}
            sudo systemctl restart nginx
            rm -rf /home/frontend/${{ env.SUBDOMAIN_ADDRESS }}
            pm2 delete stage-nextjs-app-${{ github.event.number }}